<?php
defined('WEKIT_VERSION') or exit(403);
Wind::import('ADMIN:library.AdminBaseController');
/**
 * 后台访问入口
 *
 * generated by phpwind.com
 */
class ManageController extends AdminBaseController {
	
	public function beforeAction($handlerAdapter) {
		parent::beforeAction($handlerAdapter);
		//TODO do something before all the action
	}
	
	public function run() {
	    $status=$this->getInput("status");
        $where="";
        if($status){
            $where="status=".$status;
        }
        $perpage="10";//每页显示条数
        $page = $this->getInput("page");
        $page || $page=1; //当前页码
        $data=$this->_mdemandDao()->getList($page*$perpage,($page-1)*$perpage,$where);
        $this->setOutput($data,"data");
        $this->setOutput($perpage,"perpage");
        $this->setOutput($page,"curr");
        $this->setOutput(ceil($this->_mdemandDao()->getCount() / $perpage),"pages");
	}

	public function deleteAction(){
        $id=$this->getInput("id");
    }

    public function statusAction(){
        $status=$this->getInput("status");
        $id=$this->getInput("id");
    }

    public function showAction(){
        $status=$this->getInput("status");
        $id=$this->getInput("id");
    }

    private function _mdemandDao(){
        return Wekit::load('SRC:extensions.mdemand.service.dao.App_Mdemand_MdemandDao');
    }
}

?>