<?php
defined('WEKIT_VERSION') or exit(403);
Wind::import('ADMIN:library.AdminBaseController');
Wind::import('SRC:extensions.mADs.admin.tJsonReturn');
/**
 * 后台访问入口
 *
 * generated by phpwind.com
 */
class ManageController extends AdminBaseController {
	use tJsonReturn;
	public function beforeAction($handlerAdapter) {
		parent::beforeAction($handlerAdapter);
		//TODO do something before all the action
	}
	
	public function run() {
	    $status=$this->getInput("status");
        $where=1;
        if($status||$status===0){
            $where="status=".$status;
        }
        $perpage="10";//每页显示条数
        $page = $this->getInput("page");
        $page || $page=1; //当前页码
        $data=$this->_mdemandDao()->getList($page*$perpage,($page-1)*$perpage,$where);
        $this->setOutput($data,"data");
        $this->setOutput($perpage,"perpage");
        $this->setOutput($page,"curr");
        $this->setOutput(ceil($this->_mdemandDao()->getCount() / $perpage),"pages");
	}

    public function deleteAction(){
        $id=$this->getInput('id');
        $res=$this->_mdemandDao()->delete($id);
        if($res){
            $this->success("删除成功!");
        }else{
            $this->error("删除失败！");
        }
        $this->setTemplate("");
    }

    public function statusAction(){
        $id=$this->getInput("id");
        $data["status"]=$this->getInput("status");
        if($data['status']==1){
            $data["design_name"]=$this->getInput("design_name");
            $data["design_type"]=$this->getInput("design_type");
            $data["sex"]=$this->getInput("sex");
        }
        $res=$this->_mdemandDao()->update($id,$data);
        if($res){
            $this->success("更新成功!");
        }else{
            $this->error("更新失败！");
        }
        $this->setTemplate("");
    }

    public function showAction(){
        $id=$this->getInput("id");
        $data=$this->_mdemandDao()->get($id);
        $this->setOutput($data,"data");
    }

    private function _mdemandDao(){
        return Wekit::load('SRC:extensions.mdemand.service.dao.App_Mdemand_MdemandDao');
    }
}

?>