<?php
defined('WEKIT_VERSION') or exit(403);
Wind::import('ADMIN:library.AdminBaseController');
Wind::import('SRC:extensions.mModel.admin.tJsonReturn');
Wind::import('SRC:extensions.mModel.admin.tValidate');
/**
 * 后台访问入口
 *
 * generated by phpwind.com
 */
class ManageController extends AdminBaseController {
    use tJsonReturn,tValidate;
	
	public function beforeAction($handlerAdapter) {
		parent::beforeAction($handlerAdapter);
	}
	
	public function run() {
	    $type_id=$this->getInput("type_id");
        $type_id|| $type_id=0;
        $types=$this->typeDao()->getList();
        $this->setOutput($types,"types");
        $this->setOutput($type_id,"type_id");

	}

    public function addAction(){
        $type_id=$this->getInput("type_id");
        if (!$type_id){
            $this->showError("请先选择模型类别！");
        }
        $type=$this->typeDao()->get($type_id);
        $tmp=["style","version","img_type","light"];
        foreach ($type as $k => $v){
            if (in_array($k,$tmp)){
                $this->setOutput(explode(",",$v),$k);
            }
        }
        $this->setOutput($type,"type");

//        print_r($type);
    }

    public function deleteAction(){

    }

    public function editAction(){

    }

    private function typeDao(){
        return Wekit::load('SRC:extensions.mModel.service.dao.TypeDao');
    }

    private function cateDao(){
        return Wekit::load('SRC:extensions.mModel.service.dao.CategoryDao');
    }

    private function itemDao(){
        return Wekit::load('SRC:extensions.mModel.service.dao.ItemDao');
    }

}

?>