<?php
defined('WEKIT_VERSION') or exit(403);
Wind::import('ADMIN:library.AdminBaseController');
Wind::import('SRC:extensions.mModel.admin.tJsonReturn');
Wind::import('SRC:extensions.mModel.admin.tValidate');
/**
* 后台访问入口
*
* generated by phpwind.com
*/
class ManageController extends AdminBaseController {
    use tJsonReturn,tValidate;
    
    /**
    * @param AbstractWindRouter $handlerAdapter
    */
    public function beforeAction($handlerAdapter) {
        parent::beforeAction($handlerAdapter);
    }
    
    public function run() {
        list($type_id,$page)=$this->getInput("type_id","page");
        $type_id|| $type_id=0;
        $types=$this->typeDao()->getList();
        $this->setOutput($types,"types");
        $this->setOutput($type_id,"type_id");

        if($type_id){
            $page || $page=1;
            $perpage=10;
            $this->itemDao()->getList("tid=".$type_id,$page*$perpage,($page-1)*$perpage);

        }
        
        
    }
    
    /**
    * 添加模型
    */
    public function addAction(){
        $type_id=$this->getInput("type_id");
        if (!$type_id){
            $this->showError("请先选择模型类别！");
        }
        $token=$this->getInput("csrf_token");
        if(!$token){
            $type=$this->typeDao()->get($type_id);
            $tmp=["style","version","img_type","light"];
            foreach ($type as $k => $v){
                if (in_array($k,$tmp)){
                    $this->setOutput(explode(",",$v),$k);
                }
            }
            $this->setOutput($type,"type");
            $cate=$this->cateDao()->getList("pid=0");
            $this->setOutput($cate,"cate");
            $this->setTemplate("manage_add");
        }else{
            $this->setTemplate("");
            $field=['cid','name','style','version','pictures','img_type','light','price','file','description'];
            $data=$this->getInput($field,"POST",true);
            $data['uid']=$this->loginUser->uid;
            $data['tid']=$type_id;
            if($this->itemDao()->add($data)){
                $this->success("添加成功！");
            }else{
                $this->error("添加失败！");
            }
        }
    }
    
    public function uploadAction(){
        
    }
    
    
    public function deleteAction(){
        
    }
    
    public function editAction(){
        
    }
    
    private function typeDao(){
        return Wekit::load('SRC:extensions.mModel.service.dao.TypeDao');
    }
    
    private function cateDao(){
        return Wekit::load('SRC:extensions.mModel.service.dao.CategoryDao');
    }
    
    private function itemDao(){
        return Wekit::load('SRC:extensions.mModel.service.dao.ItemDao');
    }
    
}

?>