<?php
defined('WEKIT_VERSION') or exit(403);
Wind::import('ADMIN:library.AdminBaseController');
/**
 * 后台访问入口
 *
 * generated by phpwind.com
 */
class ManageController extends AdminBaseController {
	
	public function beforeAction($handlerAdapter) {
		parent::beforeAction($handlerAdapter);
		//TODO do something before all the action
	}
	
	public function run() {
		//TODO Insert your code here!
		$userGroup = Wekit::load('usergroup.PwUserGroups');
		$groups = $userGroup->getAllGroups();
		$groupTypes = $userGroup->getTypeNames();
		foreach($groupTypes as $typeK => $typeV) {
			foreach($groups as $v) {
				if($typeK == $v['type']) {
					$d[$typeK]['name'] = $typeV;
					$d[$typeK][$v['gid']] = $v;
				}
			}
		}
		$this->setOutput($d, 'groups');
		$this->setOutput($this->set('group'), 'group');
	}
	
	public function postAction() {
		$this->set('group', false, true, $this->getInput('group', 'post'));
		$this->showMessage('配置提交成功！', '', true);
	}
	
	public function dateleAction() {
	
	}
	
	public function outAction() {
		list( $tid, $tids ) = $this->getInput( array( 'tid', 'tids' ), 'post' );
		if( !$tid ) { $this->showError( '请填写聚合帖ID' ); }
		if( !$tids ) { $this->showError( '请填写被聚合帖的帖ID' ); }
		if( $this->_getJuhe()->get( $tid ) == false ) { $this->showError( '聚合帖不存在' ); }
		if( !$this->_getJuhe()->isTid( $tid, $tids ) ) { $this->showError( '您删除的被聚合帖ID不存在' ); }
		$dm = $this->_getJuheDm();
		$dm->setTid( $tid );
		$dm->setType( $this->_getJuhe()->daletetype( $tid, $tids ) );
		$dm->setTids( $this->_getJuhe()->daleteTid( $tid, $tids ) );
		$this->_getJuhe()->update( $dm );
		$this->showMessage( '删除成功' );
	}
	
	private function _getJuhe() {
		return Wekit::loadDao('EXT:MedzExt20131221.service.App_Medz_Ext20131221_Juhe');
	}
	
	private function _getJuheDm() {
		return Wekit::load('EXT:MedzExt20131221.service.dm.App_Medz_Ext20131221_JuheDm');
	}
	
	private function set($name, $field=false, $write=false, $data=array()) {
		$script = Wekit::load('EXT:MedzExt20131221.service.helps.App_Medz_Helps');
		return $script->medz($name, $field, $write, $data);
	}
}