<?php
defined('WEKIT_VERSION') or exit(403);
Wind::import('ADMIN:library.AdminBaseController');
Wind::import('SRC:extensions.mADs.admin.tJsonReturn');
/**
 * 后台访问入口
 *
 * generated by phpwind.com
 */
class ManageController extends AdminBaseController {
    use tJsonReturn;
	
	public function beforeAction($handlerAdapter) {
		parent::beforeAction($handlerAdapter);
		//TODO do something before all the action
	}

    /**
     * 广告列表显示页面
     * @author mohuishou<1@lailin.xyz>
     */
	public function run() {
        $type_id=$this->getInput("type_id");

        if($type_id){
            $type=$this->_typeDao()->get($type_id);
            $data=$this->_itemDao()->getList('type_id='.$type_id,0,20);
        }else{
            $type='';
            $data=[];
        }
        $this->setOutput($data,"data");
        $this->setOutput($type,"selected_type");
        $type_data=$this->_typeDao()->getAll();
        $this->setOutput([
            1=>"图片广告",
            2=>"中央弹窗广告",
            3=>"右下角弹窗广告",
            4=>"广告代码",
            5=>"图片画廊"
        ],"types_option");
        $this->setOutput([
            1=>"新窗口",
            2=>"当前窗口"
        ],"open_types");
        $this->setOutput($type_data,"types");
        $this->setOutput($type_id,"type_id");
        $this->setTemplate("manage_run");

    }


    private function _typeDao(){
        return Wekit::load('SRC:extensions.mADs.service.dao.App_MADs_TypeDao');
    }



    private function _itemDao(){
        return Wekit::load('SRC:extensions.mADs.service.dao.App_MADs_ItemDao');
    }


    public function addAction(){
	    $token=$this->getInput("csrf_token");
        $type_id=$this->getInput("type_id");
        if(!$token){
            $types=$this->_typeDao();
            $this->setOutput($type_id,"type_id");
            if($type_id){
                $type=$this->_typeDao()->get($type_id);
            }else{
                $type='';
            }
            $this->setOutput($type,"selected_type");
            $type_data=$types->getAll();
            $this->setOutput($type_data,"types");
            $this->setOutput([
                1=>"图片广告",
                2=>"中央弹窗广告",
                3=>"右下角弹窗广告",
                4=>"广告代码",
                5=>"图片画廊"
            ],"types_option");
            $this->setOutput([
                1=>"新窗口",
                2=>"当前窗口"
            ],"open_types");
            $this->setTemplate("manage_add");
        }else{
            $this->setTemplate('');
            $data['title']=$this->getInput('title');
            $data['link']=$this->getInput('link');
            $data['imgpath']=$this->getInput('path');
            $data['type_id']=$type_id;
            $data['description']=$this->getInput('description');
            $data['window_title']=$this->getInput('window_title');
            $data['script']=$this->getInput('script');
            $res=$this->_itemDao()->add($data);
            if($res){
                $this->success("新增成功!",$data);
            }else{
                $this->error("新增失败！");
            }
        }
    }

    public function deleteAction(){
        $id=$this->getInput('id');
        $res=$this->_itemDao()->delete($id);
        if($res){
            $this->success("删除成功!");
        }else{
            $this->error("删除失败！");
        }
        $this->setTemplate("");
    }

    public function editAction(){
        $token=$this->getInput("csrf_token");
        $type_id=$this->getInput("type_id");
        $ad_id=$this->getInput("ad_id");
        if(!$token){
            $ad_data=$this->_itemDao()->get($ad_id);
            $this->setOutput($ad_data,'data');
            $type_id || $type_id=$ad_data['type_id'];
            $types=$this->_typeDao();
            $this->setOutput($type_id,"type_id");
            if($type_id){
                $type=$this->_typeDao()->get($type_id);
            }else{
                $type='';
            }
            $this->setOutput($type,"selected_type");
            $type_data=$types->getAll();
            $this->setOutput($type_data,"types");
            $this->setOutput([
                1=>"图片广告",
                2=>"中央弹窗广告",
                3=>"右下角弹窗广告",
                4=>"广告代码",
                5=>"图片画廊"
            ],"types_option");
            $this->setOutput([
                1=>"新窗口",
                2=>"当前窗口"
            ],"open_types");


            $this->setTemplate("manage_edit");
        }else{
            $this->setTemplate('');
            $data['link']=$this->getInput('link');
            $data['imgpath']=$this->getInput('path');
            $data['type_id']=$type_id;
            $data['description']=$this->getInput('description');
            $data['window_title']=$this->getInput('window_title');
            $data['script']=$this->getInput('script');
            $res=$this->_itemDao()->update($ad_id,$data);
            if($res){
                $this->success("更新成功!",$data);
            }else{
                $this->error("更新失败！");
            }
        }
    }


}

?>