<?php
defined('WEKIT_VERSION') or exit(403);
/**
* 前台入口
*
* generated by phpwind.com
*/
class IndexController extends PwBaseController {
    
    public function beforeAction($handlerAdapter) {
        parent::beforeAction($handlerAdapter);
    }
    
    public function run() {
        //首先需要模型大的分类
        $type_id=$this->getInput("type_id");
        if (!$type_id){
            $this->showError("请先选择模型类别！");
        }

        //分类信息
        $type=$this->typeDao()->get($type_id);
        $this->setOutput($type,"type");
        
        //查询条件
        $where="tid={$type_id}";
        $cid=$this->getInput("cid");
        if($cid){
            $where .=" AND cid=".$cid;
        }
        
        //排序方式
        $order=$this->getInput("order");
        switch($order){
            case 1:
                $order="updated_time desc";
                break;
            case 2:
                $order="download desc";
                break;
            default:
                $order="updated_time desc";
                break;
        }

        $page=$this->getInput("page");
        $page || $page=1;
        $perpage=10;

        $items=$this->itemDao()->getList($where,$page*$perpage,($page-1)*$perpage,$order);

        //获取所有的模型类别信息
        $cates=$this->getCate($type_id);
        
    }
    
    protected function getCate($tid){
        $parent=$this->cateDao()->getList("tid={$tid} AND pid=0");
        $data=[];
        foreach($parent as $v){
            $data['parent']=$v;
            $data['children']=[];
            if($v['id']){
                $data['children']=$this->cateDao()->getList("tid={$tid} AND pid=".$v['id']);
                
            }
        }
        return $data;
    }
    
    
    private function typeDao(){
        return Wekit::load('SRC:extensions.mModel.service.dao.TypeDao');
    }
    
    private function cateDao(){
        return Wekit::load('SRC:extensions.mModel.service.dao.CategoryDao');
    }
    
    private function itemDao(){
        return Wekit::load('SRC:extensions.mModel.service.dao.ItemDao');
    }
    
    private function downloadDao(){
        return Wekit::load('SRC:extensions.mModel.service.dao.DownloadDao');
    }
}

?>