<?php
defined('WEKIT_VERSION') or exit(403);
Wind::import('ADMIN:library.AdminBaseController');
/**
 * 后台访问入口
 *
 * generated by phpwind.com
 */
class ManageController extends AdminBaseController {
	
	public function beforeAction($handlerAdapter) {
		parent::beforeAction($handlerAdapter);
		//TODO do something before all the action
	}
	
	public function run() {
		//TODO Insert your code here!
	}

	public function addAction(){
        $token=$this->getInput("csrf_token");
        if ($token){

        }else{
            $this->setTemplate("manage_add");
        }
	}

	public function edit(){

	}

	public function delete(){
		
	}

    protected function _navDao(){
        return Wekit::load('SRC:extensions.mADs.service.dao.App_MTopNav_MTopNavDao');
    }
}


?>